name:                property-based-testing-examples
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/marcosh/property-based-testing-examples.git
license:             BSD3
author:              Marco Perone
maintainer:          pasafama@gmail.com
copyright:           2020 Marco Perone
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

tests:
  sort-prop-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - extra
      - hspec
      - QuickCheck
      - safe
